#!/bin/bash

cp -v ./source/cursedmenu/*.cmd build/Release/source/cursedmenu/.

cd examples

if [ "$#" -gt 0 ]; then
    ../build/Release/source/cursedmenu/cursedmenu "$@"
else
    ../build/Release/source/cursedmenu/cursedmenu -m default.json
fi
