#!/bin/bash

if [ "$1" = "-r" ]; then
	PRESET="--preset=conan-release"
	RELEASE_FOLDER="Release"
else
	PRESET="--preset=conan-release"
	RELEASE_FOLDER="Release"
fi

./clean

git pull

conan install . --build=missing

cmake . "${PRESET}"

source build/${RELEASE_FOLDER}/generators/conanbuild.sh

cmake --build . "${PRESET}"

source build/${RELEASE_FOLDER}/generators/deactivate_conanbuild.sh

#ctest --test-dir test

#source ./Release/generators/deactivate_conanbuild.sh
