#!/bin/bash

set -e

if [ "$1" = "-d" ]; then
    PRESET="conan-debug"
    BUILD_FOLDER="Debug"
else
    PRESET="conan-release"
    BUILD_FOLDER="Release"
fi

./clean

conan install . --build=missing -s build_type=${BUILD_FOLDER}

cmake --preset=${PRESET}

source build/${BUILD_FOLDER}/generators/conanbuild.sh

cmake --build --preset=${PRESET}

source build/${BUILD_FOLDER}/generators/deactivate_conanbuild.sh

# ctest --preset=${PRESET}
